blog/urls.py
from django.conf.urls import url
from . import views


app_name = 'blog'
urlpatterns = [
	url(r'^$', views.post_list, name='post_list'),
	url(r'^index/$', views.post_list, name='index'),
	url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
	url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, 
		name='add_comment_to_post'),
	url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
	url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
	url(r'^post/(?P<pk>\d+)/delete/$', views.post_delete, name='post_delete'),
	url(r'^post/new/$', views.post_new, name='post_new'),
	url(r'^drafts/$', views.post_draft_list, name='post_draft_list'),
	url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
	url(r'^comment/(?P<pk>\d+)/delete/$', views.comment_delete, name='comment_delete'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import django.contrib.auth.views


admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', django.contrib.auth.views.login, 
    	name='login'),
    url(r'^accounts/logout/$', django.contrib.auth.views.logout, 
        name='logout', kwargs={'next_page': '/'}),
    url(r'', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
	author = models.ForeignKey('auth.User')
	title = models.CharField(max_length = 200)
	text = models.TextField()
	created_date = models.DateTimeField(default = timezone.now)
	published_date = models.DateTimeField(blank = True, null = True)


	def publish(self):
		self.published_date = timezone.now()
		self.save()


	def approved_comments(self):
		return self.comments.filter(approved_comment = True)


	def __str__(self):
		return self.title


class Comment(models.Model):
	post = models.ForeignKey(Post, related_name='comments')
	author = models.CharField(max_length = 200)
	text = models.TextField()
	created_date = models.DateTimeField(default = timezone.now)
	approved_comment = models.BooleanField(default = False)


	def approve(self):
		self.approved_comment = True
		self.save()


	def __str__(self):
		return self.text

blog/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):

	class Meta:
		model = Post
		fields = ('title', 'text',)


class CommentForm(forms.ModelForm):

	class Meta:
		model = Comment
		fields = ('author', 'text',)

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from .models import Post, Comment
from .forms import PostForm, CommentForm


def post_list(request):
	posts = Post.objects.filter(published_date__lte = 
		timezone.now()).order_by('-published_date')
	context = {
		'posts': posts,
	}
	return render(request, 'blog/post_list.html', context)


def post_detail(request, pk):
	post = get_object_or_404(Post, pk=pk)
	context = {
		'post': post,
	}
	return render(request, 'blog/post_detail.html', context)


@login_required
def post_new(request):
	if request.method == "POST":
		form = PostForm(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.save()
			return redirect('blog:post_detail', pk=post.pk)
	else:
		form = PostForm()
	context = {
		'form': form,
	}
	return render(request, 'blog/post_edit.html', context)


@login_required
def post_edit(request, pk):
	post = get_object_or_404(Post, pk=pk)
	if request.method == "POST":
		form = PostForm(request.POST, instance=post)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.published_date = timezone.now()
			post.save()
			return redirect('blog:post_detail', pk=post.pk)
	else:
		form = PostForm(instance = post)
	context = {
		'form': form,
	}
	return render(request, 'blog/post_edit.html', context)


@login_required
def post_draft_list(request):
	posts = Post.objects.filter(published_date__isnull = True).order_by('-created_date')
	context = {
		'posts': posts,
	}
	return render(request, 'blog/post_draft_list.html', context)


@login_required
def post_publish(request, pk):
	post = get_object_or_404(Post, pk=pk)
	post.publish()
	return redirect('blog:post_detail', pk=pk)


@login_required
def post_delete(request, pk):
	post = get_object_or_404(Post, pk=pk)
	post.delete()
	return redirect('blog:post_list')


def add_comment_to_post(request, pk):
	post = get_object_or_404(Post, pk=pk)
	if request.method == "POST":
		form  = CommentForm(request.POST)
		if form.is_valid():
			comment = form.save(commit=False)
			comment.post = post
			comment.save()
			return redirect('blog:post_detail', pk=post.pk)
	else:
		form = CommentForm()
	context = {
		'form': form,
	}
	return render(request, 'blog/add_comment_to_post.html', context)


@login_required
def comment_approve(request, pk):
	comment = get_object_or_404(Comment, pk=pk)
	comment.approve()
	return redirect('blog:post_detail', pk=comment.post.pk)


@login_required
def comment_delete(request, pk):
	comment = get_object_or_404(Comment, pk=pk)
	post_pk = comment.post.pk
	comment.delete()
	return redirect('blog:post_detail', pk=post_pk)

blog/templates/blog/add_comment_to_post.html
{% extends 'blog/base.html' %}

{% block content %}
	<h1>New Comment</h1>
	<form method="post" class="post-form">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="save btn btn-default">Send</button>
	</form>
{% endblock %}

blog/templates/blog/base.html
{% load staticfiles %}
<html>
	<head>
		<title>Django Girls blog</title>
		<link href="http://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
		<link rel="stylesheet" href="{% static 'blog/style.css' %}">
	</head>
	<body>
		<div class="page-header">
			{% if user.is_authenticated %}
				<a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
				<a href="{% url 'blog:post_draft_list' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
				<p class="top-menu">Hello {{ user.username }} <small>(<a href="{% url 'logout' %}">Logout </a>)</small></p>
			{% else %}
				<a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
			{% endif %}
			<h1><a href="{% url 'blog:post_list' %}">Django Girls Blog</a></h1>
		</div>
		<div class="content container">
			<div class="row">
				<div class="col-md-8">
					{% block content %}
					{% endblock %}
				</div>
			</div>
		</div>

	</body>
</html>

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
	<div class="post">
		{% if user.is_authenticated %}
			<a class="btn btn-danger right" href="{% url 'blog:post_delete' pk=post.pk %}"><span class="glyphicon glyphicon-trash"></span></a>
			<a class="btn btn-default right" href="{% url 'blog:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
		{% endif %}
		{% if post.published_date %}
			<div class="date">
				<p>Published: {{ post.published_date|date:'d-m-Y' }} </p>
			</div>
		{% else %}
			<a class="btn btn-default right" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>

		{% endif %}
		<h1>{{ post.title }}</h1>
		<p>{{ post.text|linebreaks }} </p>
	</div>
	<hr>
		<a class="btn btn-default" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Add Comment</a>
		{% for comment in post.comments.all %}
			{% if user.is_authenticated or comment.approved_comment %}
				<div class="comment">
					<div class="date">
						{{ comment.created_date }}
						{% if not comment.approved_comment %}
							<a class="btn btn-danger" href="{% url 'blog:comment_delete' pk=comment.pk %}"><span class="glyphicon glyphicon-trash"></span></a>
							<a class="btn btn-default" href="{% url 'blog:comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
						{% endif %}
					</div>
					<strong>{{ comment.author }}</strong>
					<p>{{ comment.text|linebreaks }}</p>
				</div>
			{% endif %}
		{% empty %}
			<p>No comments here yet.</p>
		{% endfor %}
{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}

{% block content %}
	{% for post in posts %}
		<div class="post">
			<p class="date">Created: {{ post.created_date|date:'d-m-Y' }}</p>
			<h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
			<p>{{ post.text|truncatechars:200 }}</p>
		</div>
	{% empty %}
		<div class="post">
			<h1>There are no unpublished posts.</h1>
		</div>
	{% endfor %}
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
	<h1>New Post</h1>
	<form method="post" class="post-form">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="save btn btn-default">Save</button>
	</form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
	{% for post in posts %}
		<div class="post">
			<div class="date">
				<p>Published: {{ post.published_date|date:'d-m-Y' }} </p>
			</div>
			<h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }} </a></h1>
			<p>{{ post.text|truncatechars:200 }} </p>
			<a href="{% url 'blog:post_detail' pk=post.pk %}">Comments: {{ post.approved_comments.count }}</a>
		</div>
	{% endfor %}
{% endblock %}